import { useState } from 'react';
import type { NextPage } from 'next'
import type { MouseEventHandler } from 'react'
import Head from 'next/head'
import { LazyImage } from '../components/RandomFox'

const random = () => Math.floor(Math.random()*123) + 1;
const generateId = ()=>Math.random().toString(36).substring(2,9);
type ImageItem = { id:string, url:string };
const Home: NextPage = () => {

  const [images, setImages] = useState<Array<ImageItem>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event)=>{
    event.preventDefault();
    const newImageItem: ImageItem = {id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg`};
    setImages([...images, newImageItem]);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Hello Platzi
        </h1>
        <button onClick={addNewFox}>Add new fox</button>
        {images.map(({id, url}) => (
          <div key={id} className='p-4'>
            <LazyImage 
              src={url} 
              onClick={()=> {console.log('Hola')}} 
              onLazyLoad={(img)=>{console.log('Imagen cargada')}}
              />
          </div>
        ))}
        
      </main>
    </div>
  )
}

export default Home
