import type { NextPage } from 'next'
import Head from 'next/head'
import { RandomFox } from '../styles/components/RandomFox'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Hello Platzi
        </h1>
        <RandomFox />
      </main>
    </div>
  )
}

export default Home
